{% set data = load_setup_py_data() %}

package:
  name: "alpaca_kernel_2"
  version: {{ data.get('version') }}

source:
  path: .

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel

  run:
    - python
    - numpy
    - matplotlib
    - pyserial
    - ipython
    - comm
    - traitlets
    - jupyter_client
    - jupyter_core
    - tornado
    - appnope  # [osx]
    - pyzmq
    - psutil
    - packaging
    
about:
  home: https://github.com/NB-TUDelft/alpaca_kernel_2
  license: MIT
  license_family: MIT
  summary: jupyter_micropython_kernel and IPyKernel
